### ISSUE TITLE
images missing

### ISSUE THREAD

**Issue by psifertex** [404d/autoutils#1]
Images loaded via the plugin.json appear to be missing. Likely they need to be updated to urls like:
`https://raw.githubusercontent.com/404d/autoutils/master/extras/discover_arg_before.png`

**Comment by psifertex** [comment]
*ping*

**Comment by 404d** [comment]
Held off on fixing this since I wanted to at least add more functionality at the same time, but I haven't been able to work on the particular project where I had use for this.

Fixed now, will make a PR soon.

**Comment by psifertex** [comment]
Thanks. I'll update the plugin in the repo.
